# Generated by Django 6.0.5 on 2026-05-16 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntakeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('country_of_origin', models.CharField(max_length=255)),
                ('preferred_language', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('current_location', models.CharField(blank=True, max_length=255)),
                ('detained', models.BooleanField(default=False)),
                ('immigration_court', models.CharField(blank=True, max_length=255)),
                ('a_number', models.CharField(blank=True, max_length=50)),
                ('next_hearing_date', models.DateField(blank=True, null=True)),
                ('fear_of_return_summary', models.TextField()),
                ('past_harm_summary', models.TextField(blank=True)),
                ('family_members_included', models.BooleanField(default=False)),
                ('consent_acknowledged', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('new', 'New'), ('conflict_check', 'Needs Conflict Check'), ('translation_review', 'Needs Translation Review'), ('legal_review', 'Needs Legal Review'), ('accepted', 'Accepted'), ('referred', 'Referred'), ('closed', 'Closed')], default='new', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
