# Generated by Django 6.0.5 on 2026-05-17 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intakesubmission',
            name='date_of_birth',
            field=models.DateField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='intakesubmission',
            name='next_hearing_date',
            field=models.DateField(blank=True, max_length=100),
        ),
    ]
