# Generated by Django 6.0.5 on 2026-05-17 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0002_alter_intakesubmission_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intakesubmission',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='intakesubmission',
            name='next_hearing_date',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
