# Generated by Django 6.0.5 on 2026-08-07 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0005_intakesubmission_language_translation_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intakesubmission',
            options={'permissions': [('access_dashboard', 'Can access the case manager dashboard')]},
        ),
    ]
