# Generated by Django 6.0.5 on 2026-08-14 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0008_intakesubmission_assigned_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intakesubmission',
            options={'permissions': [('access_dashboard', 'Can access the case manager dashboard'), ('change_case_status', 'Can change case status')]},
        ),
        migrations.AddField(
            model_name='intakesubmission',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intakesubmission',
            name='status_changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changed_cases', to=settings.AUTH_USER_MODEL),
        ),
    ]
